{
	"version": 1597708129,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/backgroundmenu-sheet0.png",
		"images/btplay-sheet0.png",
		"images/personagem-sheet0.png",
		"images/mainbackground.png",
		"images/ball-sheet0.png",
		"images/ball-sheet1.png",
		"images/bonecos-sheet0.png",
		"images/bonecos-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/tiledbackground.png",
		"images/level-sheet0.png",
		"images/start-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/proximo-sheet0.png",
		"images/gameover-sheet0.png",
		"images/btn_direita-sheet0.png",
		"images/btn_esquerda-sheet0.png",
		"images/spritefont.png",
		"images/gamepad-sheet0.png",
		"images/gamepad_middle-sheet0.png",
		"images/sombra-sheet0.png",
		"images/jogador-sheet0.png",
		"images/textmatches.png",
		"images/sprite-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/particles.png",
		"images/logolied-sheet0.png",
		"images/estrela-sheet0.png",
		"images/estrela-sheet1.png",
		"images/creditos-sheet0.png",
		"media/amarelo.ogg",
		"media/azul.ogg",
		"media/branco.ogg",
		"media/preto.ogg",
		"media/verde.ogg",
		"media/vermelho.ogg",
		"media/bgsom.ogg",
		"media/gravador de voz_18 (online-audio-converter.com).ogg",
		"media/gravador de voz_24 (1) (online-audio-converter.com).ogg",
		"media/aud-20200817-wa0085 (1) (online-audio-converter.com).ogg",
		"media/aud-20200817-wa0080 (1) (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}